---
- hosts: vagrant
  sudo: yes
  tasks:
    - name: ensure recent package list
      apt: update_cache=yes
    - name: install essential Python packages
      apt: pkg=$item state=present
      with_items:
        - python-pip
        - python-virtualenv
