---
- hosts: vagrant
  connection: ssh
  sudo: yes

  vars:
    - hbase_release: hbase-0.94.9
    - hbase_archive: '{{ hbase_release }}.tar.gz'
    - hbase_home_dir: '/home/vagrant/{{ hbase_release }}'
    - hbase_data_dir: /data/hbase
    - zookeeper_data_dir: /data/zk

  tasks:
    - name: ensure recent package list
      apt: update_cache=yes

    - name: install essential Python packages
      apt: pkg='{{ item }}' state=present
      with_items:
        - python-pip
        - python-virtualenv
        - python-software-properties
        - python-dev

    - name: install Python client libraries for Thrift and HBase
      pip: name='{{ item }}' state=present
      with_items:
        - thrift
        - happybase

    - name: add Java PPA
      apt_repository: repo=ppa:webupd8team/java state=present

    - name: automatically accept Java license
      shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

    - name: install Java 7
      apt: pkg='{{ item }}' state=present update_cache=yes
      with_items:
        - oracle-java7-installer
        - oracle-java7-set-default
        - jython

    - name: fix /etc/hosts
      lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1\s+(.*)$' line='127.0.0.1 \1' backrefs=yes state=present

    - name: download HBase release {{ hbase_release }}
      get_url: url='http://ftp.ps.pl/pub/apache/hbase/stable/{{ hbase_archive }}' dest='/home/vagrant/{{ hbase_archive }}'

    - name: create HBase-related directories
      file: path='{{ item }}' state=directory
      with_items:
        - '{{ hbase_data_dir }}'
        - '{{ zookeeper_data_dir }}'

    - name: extract HBase archive
      command: tar xzf '/home/vagrant/{{ hbase_archive }}' creates='{{ hbase_home_dir }}'

    - name: write HBase config file
      template: src=templates/hbase-site.xml.j2 dest='{{ hbase_home_dir }}/conf/hbase-site.xml'

    - name: set JAVA_HOME environment variable
      lineinfile: dest='{{ hbase_home_dir }}/conf/hbase-env.sh' regexp='^#?\s*export JAVA_HOME=(.*)$' line='export JAVA_HOME=/usr/lib/jvm/java-7-oracle/jre' state=present

    - name: start HBase
      command: '{{ hbase_home_dir }}/bin/start-hbase.sh'

    - name: start Thrift server
      shell: '{{ hbase_home_dir }}/bin/hbase-daemon.sh start thrift'
