---
- hosts: vagrant
  sudo: yes
  tasks:
    - name: ensure recent package list
      apt: update_cache=yes
    - name: install essential Python packages
      apt: pkg=$item state=present
      with_items:
        - python-pip
        - python-virtualenv
        - python-software-properties
    - name: add Java PPA
      apt_repository: repo=ppa:webupd8team/java state=present
